### ISSUE TITLE
长时间开机后电脑无法关机或睡眠

### ISSUE THREAD

**Issue by CraKeyBoy** [hahn1994/Dell7537_Laptop_Hackintosh#1]
这个固件是在win下更新吗？有详细步骤吗？

**Comment by hahn1994** [comment]
你看他提供的文件，在DOS、EFI、WIN下都有不同的执行文件，windows下可以更新
更新方法原帖中有，英文不好的话，可以看我的帖子http://bbs.pcbeta.com/forum.php?mod=redirect&goto=findpost&ptid=1677097&pid=45686823

**Comment by CraKeyBoy** [comment]
谢啦(●'◡'●)
